# Generated by Django 5.0.6 on 2024-06-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sendmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.IntegerField()),
                ('text', models.TextField(editable=False)),
                ('filetype', models.CharField(max_length=255)),
                ('fileid', models.TextField(editable=False)),
                ('datesend', models.DateTimeField()),
                ('userswhom_id', models.TextField()),
            ],
            options={
                'db_table': 'sendmessages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.IntegerField()),
                ('category', models.TextField()),
                ('subcategory', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('photoid', models.TextField()),
                ('count', models.IntegerField()),
                ('onsell', models.BooleanField()),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
