# Generated by Django 5.0.6 on 2024-06-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quest', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'FAQ',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='sendmessage',
            options={'managed': False, 'verbose_name': 'Отправленные сообщения', 'verbose_name_plural': 'Отправленные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'managed': False, 'verbose_name': 'Товар', 'verbose_name_plural': 'Товар'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
