# Generated by Django 5.0.6 on 2024-06-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testprog', '0002_faq_alter_sendmessage_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faq',
            table='faq',
        ),
    ]
