# Generated by Django 5.0.6 on 2024-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprog', '0003_alter_faq_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('dateadded', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Администраторы Telegram',
                'verbose_name_plural': 'Администраторы Telegram',
                'db_table': 'tgadmins',
                'managed': False,
            },
        ),
    ]
