# Generated by Django 5.0.6 on 2024-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testprog', '0004_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('typedata', models.CharField(max_length=255)),
                ('values', models.TextField()),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ЛОГИ',
                'verbose_name_plural': 'ЛОГИ',
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(editable=False, max_length=255)),
                ('values', models.TextField()),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings',
                'managed': False,
            },
        ),
    ]
